[versions]
compose = "1.6.8"
material3 = "1.2.1"
activityCompose = "1.9.0"
lifecycle = "2.8.3"
navigation = "2.7.7"
hilt = "2.51.1"
hiltNav = "1.2.0"
retrofit = "2.11.0"
moshi = "1.15.1"
okhttpLogging = "4.12.0"
room = "2.6.1"
datastore = "1.1.1"
work = "2.9.0"
coil = "2.6.0"

[libraries]
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNav" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpLogging" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
work = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.14" }